DROP TABLE WF_ACTIVE_FLOW_NODE CASCADE CONSTRAINTS PURGE
CREATE TABLE WF_ACTIVE_FLOW_NODE( INSTANCE_ID NCHAR(10) NOT NULL, FLOW_NODE_ID NVARCHAR2(18) NOT NULL)
ALTER TABLE WF_ACTIVE_FLOW_NODE ADD(CONSTRAINT PK_WF_ACTIVE_FLOW_NODE PRIMARY KEY (INSTANCE_ID, FLOW_NODE_ID) USING INDEX)
DROP TABLE WF_ACTIVE_GROUP_TASK CASCADE CONSTRAINTS PURGE
CREATE TABLE WF_ACTIVE_GROUP_TASK( INSTANCE_ID NCHAR(10) NOT NULL, FLOW_NODE_ID NVARCHAR2(18) NOT NULL, ASSIGNED_GROUP_ID NCHAR(10) NOT NULL, EXECUTION_ORDER NUMBER(2,0) NOT NULL)
ALTER TABLE WF_ACTIVE_GROUP_TASK ADD(CONSTRAINT PK_WF_ACTIVE_GROUP_TASK PRIMARY KEY (INSTANCE_ID, FLOW_NODE_ID, ASSIGNED_GROUP_ID) USING INDEX)
DROP TABLE WF_ACTIVE_USER_TASK CASCADE CONSTRAINTS PURGE
CREATE TABLE WF_ACTIVE_USER_TASK( INSTANCE_ID NCHAR(10) NOT NULL, FLOW_NODE_ID NVARCHAR2(18) NOT NULL, ASSIGNED_USER_ID NCHAR(10) NOT NULL, EXECUTION_ORDER NUMBER(2,0) NOT NULL)
ALTER TABLE WF_ACTIVE_USER_TASK ADD(CONSTRAINT PK_WF_ACTIVE_USER_TASK PRIMARY KEY (INSTANCE_ID, FLOW_NODE_ID, ASSIGNED_USER_ID) USING INDEX)
DROP TABLE WF_BOUNDARY_EVENT CASCADE CONSTRAINTS PURGE
CREATE TABLE WF_BOUNDARY_EVENT( WORKFLOW_ID NCHAR(6) NOT NULL, DEF_VERSION NUMBER(8,0) NOT NULL, FLOW_NODE_ID NVARCHAR2(18) NOT NULL, BOUNDARY_EVENT_TRIGGER_ID NCHAR(4) NOT NULL, ATTACHED_TASK_ID NVARCHAR2(18) NOT NULL)
ALTER TABLE WF_BOUNDARY_EVENT ADD(CONSTRAINT PK_WF_BOUNDARY_EVENT PRIMARY KEY (WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) USING INDEX)
DROP TABLE WF_BOUNDARY_EVENT_TRIGGER CASCADE CONSTRAINTS PURGE
CREATE TABLE WF_BOUNDARY_EVENT_TRIGGER( WORKFLOW_ID NCHAR(6) NOT NULL, DEF_VERSION NUMBER(8,0) NOT NULL, BOUNDARY_EVENT_TRIGGER_ID NCHAR(4) NOT NULL, BOUNDARY_EVENT_TRIGGER_NAME NVARCHAR2(100))
ALTER TABLE WF_BOUNDARY_EVENT_TRIGGER ADD(CONSTRAINT PK_WF_BOUNDARY_EVENT_TRIGGER PRIMARY KEY (WORKFLOW_ID, DEF_VERSION, BOUNDARY_EVENT_TRIGGER_ID) USING INDEX)
DROP TABLE WF_EVENT CASCADE CONSTRAINTS PURGE
CREATE TABLE WF_EVENT( WORKFLOW_ID NCHAR(6) NOT NULL, DEF_VERSION NUMBER(8,0) NOT NULL, FLOW_NODE_ID NVARCHAR2(18) NOT NULL, EVENT_TYPE NVARCHAR2(50) NOT NULL)
ALTER TABLE WF_EVENT ADD(CONSTRAINT PK_WF_EVENT PRIMARY KEY (WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) USING INDEX)
DROP TABLE WF_FLOW_NODE CASCADE CONSTRAINTS PURGE
CREATE TABLE WF_FLOW_NODE( WORKFLOW_ID NCHAR(6) NOT NULL, DEF_VERSION NUMBER(8,0) NOT NULL, FLOW_NODE_ID NVARCHAR2(18) NOT NULL, LANE_ID NCHAR(2) NOT NULL, FLOW_NODE_NAME NVARCHAR2(100))
ALTER TABLE WF_FLOW_NODE ADD(CONSTRAINT PK_WF_FLOW_NODE PRIMARY KEY (WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) USING INDEX)
DROP TABLE WF_GATEWAY CASCADE CONSTRAINTS PURGE
CREATE TABLE WF_GATEWAY( WORKFLOW_ID NCHAR(6) NOT NULL, DEF_VERSION NUMBER(8,0) NOT NULL, FLOW_NODE_ID NVARCHAR2(18) NOT NULL, GATEWAY_TYPE NVARCHAR2(50) NOT NULL)
ALTER TABLE WF_GATEWAY ADD(CONSTRAINT PK_WF_GATEWAY PRIMARY KEY (WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) USING INDEX)
DROP TABLE WF_INSTANCE CASCADE CONSTRAINTS PURGE
CREATE TABLE WF_INSTANCE( INSTANCE_ID NCHAR(10) NOT NULL, WORKFLOW_ID NCHAR(6) NOT NULL, DEF_VERSION NUMBER(8,0) NOT NULL)
ALTER TABLE WF_INSTANCE ADD(CONSTRAINT PK_WF_INSTANCE PRIMARY KEY (INSTANCE_ID) USING INDEX)
DROP TABLE WF_INSTANCE_FLOW_NODE CASCADE CONSTRAINTS PURGE
CREATE TABLE WF_INSTANCE_FLOW_NODE( INSTANCE_ID NCHAR(10) NOT NULL, FLOW_NODE_ID NVARCHAR2(18) NOT NULL, WORKFLOW_ID NCHAR(6) NOT NULL, DEF_VERSION NUMBER(8,0) NOT NULL)
ALTER TABLE WF_INSTANCE_FLOW_NODE ADD(CONSTRAINT PK_WF_INSTANCE_FLOW_NODE PRIMARY KEY (INSTANCE_ID, FLOW_NODE_ID) USING INDEX)
DROP TABLE WF_LANE CASCADE CONSTRAINTS PURGE
CREATE TABLE WF_LANE( WORKFLOW_ID NCHAR(6) NOT NULL, DEF_VERSION NUMBER(8,0) NOT NULL, LANE_ID NCHAR(2) NOT NULL, LANE_NAME NVARCHAR2(100))
ALTER TABLE WF_LANE ADD(CONSTRAINT PK_WF_LANE PRIMARY KEY (WORKFLOW_ID, DEF_VERSION, LANE_ID) USING INDEX)
DROP TABLE WF_SEQUENCE_FLOW CASCADE CONSTRAINTS PURGE
CREATE TABLE WF_SEQUENCE_FLOW( WORKFLOW_ID NCHAR(6) NOT NULL, DEF_VERSION NUMBER(8,0) NOT NULL, SEQUENCE_FLOW_ID NVARCHAR2(20) NOT NULL, SOURCE_FLOW_NODE_ID NVARCHAR2(18) NOT NULL, TARGET_FLOW_NODE_ID NVARCHAR2(18) NOT NULL, FLOW_PROCEED_CONDITION NVARCHAR2(200), SEQUENCE_FLOW_NAME NVARCHAR2(100))
ALTER TABLE WF_SEQUENCE_FLOW ADD(CONSTRAINT PK_WF_SEQUENCE_FLOW PRIMARY KEY (WORKFLOW_ID, DEF_VERSION, SEQUENCE_FLOW_ID) USING INDEX)
DROP TABLE WF_TASK CASCADE CONSTRAINTS PURGE
CREATE TABLE WF_TASK( WORKFLOW_ID NCHAR(6) NOT NULL, DEF_VERSION NUMBER(8,0) NOT NULL, FLOW_NODE_ID NVARCHAR2(18) NOT NULL, MULTI_INSTANCE_TYPE NVARCHAR2(50) NOT NULL, COMPLETION_CONDITION NVARCHAR2(200))
ALTER TABLE WF_TASK ADD(CONSTRAINT PK_WF_TASK PRIMARY KEY (WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) USING INDEX)
DROP TABLE WF_TASK_ASSIGNED_GROUP CASCADE CONSTRAINTS PURGE
CREATE TABLE WF_TASK_ASSIGNED_GROUP( INSTANCE_ID NCHAR(10) NOT NULL, FLOW_NODE_ID NVARCHAR2(18) NOT NULL, ASSIGNED_GROUP_ID NCHAR(10) NOT NULL, EXECUTION_ORDER NUMBER(2,0) NOT NULL)
ALTER TABLE WF_TASK_ASSIGNED_GROUP ADD(CONSTRAINT PK_WF_TASK_ASSIGNED_GROUP PRIMARY KEY (INSTANCE_ID, FLOW_NODE_ID, ASSIGNED_GROUP_ID) USING INDEX)
DROP TABLE WF_TASK_ASSIGNED_USER CASCADE CONSTRAINTS PURGE
CREATE TABLE WF_TASK_ASSIGNED_USER( INSTANCE_ID NCHAR(10) NOT NULL, FLOW_NODE_ID NVARCHAR2(18) NOT NULL, ASSIGNED_USER_ID NCHAR(10) NOT NULL, EXECUTION_ORDER NUMBER(2,0) NOT NULL)
ALTER TABLE WF_TASK_ASSIGNED_USER ADD(CONSTRAINT PK_WF_TASK_ASSIGNED_USER PRIMARY KEY (INSTANCE_ID, FLOW_NODE_ID, ASSIGNED_USER_ID) USING INDEX)
DROP TABLE WF_WORKFLOW_DEFINITION CASCADE CONSTRAINTS PURGE
CREATE TABLE WF_WORKFLOW_DEFINITION( WORKFLOW_ID NCHAR(6) NOT NULL, DEF_VERSION NUMBER(8,0) NOT NULL, WORKFLOW_NAME NVARCHAR2(100) NOT NULL, EFFECTIVE_DATE NCHAR(8) NOT NULL)
ALTER TABLE WF_WORKFLOW_DEFINITION ADD(CONSTRAINT PK_WF_WORKFLOW_DEFINITION PRIMARY KEY (WORKFLOW_ID, DEF_VERSION) USING INDEX)
ALTER TABLE WF_BOUNDARY_EVENT_TRIGGER ADD(CONSTRAINT FK_WF_WORKFLOW_DEF_TRIGGER FOREIGN KEY(WORKFLOW_ID, DEF_VERSION) REFERENCES WF_WORKFLOW_DEFINITION (WORKFLOW_ID, DEF_VERSION) DEFERRABLE)
ALTER TABLE WF_LANE ADD(CONSTRAINT FK_WF_WORKFLOW_DEF_LANE FOREIGN KEY(WORKFLOW_ID, DEF_VERSION) REFERENCES WF_WORKFLOW_DEFINITION (WORKFLOW_ID, DEF_VERSION) DEFERRABLE)
ALTER TABLE WF_INSTANCE ADD(CONSTRAINT FK_WF_WORKFLOW_DEF_INSTANCE FOREIGN KEY(WORKFLOW_ID, DEF_VERSION) REFERENCES WF_WORKFLOW_DEFINITION (WORKFLOW_ID, DEF_VERSION) DEFERRABLE)
ALTER TABLE WF_SEQUENCE_FLOW ADD(CONSTRAINT FK_WF_FLOW_NODE_SEQ_TARGET FOREIGN KEY(WORKFLOW_ID, DEF_VERSION, TARGET_FLOW_NODE_ID) REFERENCES WF_FLOW_NODE (WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) DEFERRABLE)
ALTER TABLE WF_SEQUENCE_FLOW ADD(CONSTRAINT FK_WF_FLOW_NODE_SEQ_SOURCE FOREIGN KEY(WORKFLOW_ID, DEF_VERSION, SOURCE_FLOW_NODE_ID) REFERENCES WF_FLOW_NODE (WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) DEFERRABLE)
ALTER TABLE WF_INSTANCE_FLOW_NODE ADD(CONSTRAINT FK_WF_INSTANCE_FLOW_NODE FOREIGN KEY(INSTANCE_ID) REFERENCES WF_INSTANCE (INSTANCE_ID) DEFERRABLE)
ALTER TABLE WF_TASK_ASSIGNED_USER ADD(CONSTRAINT FK_WF_INSTANCE_NODE_USER FOREIGN KEY(INSTANCE_ID, FLOW_NODE_ID) REFERENCES WF_INSTANCE_FLOW_NODE (INSTANCE_ID, FLOW_NODE_ID) DEFERRABLE)
ALTER TABLE WF_TASK_ASSIGNED_GROUP ADD(CONSTRAINT FK_WF_INSTANCE_NODE_GROUP FOREIGN KEY(INSTANCE_ID, FLOW_NODE_ID) REFERENCES WF_INSTANCE_FLOW_NODE (INSTANCE_ID, FLOW_NODE_ID) DEFERRABLE)
ALTER TABLE WF_ACTIVE_FLOW_NODE ADD(CONSTRAINT FK_WF_INSTANCE_NODE_ACTIVE_NOD FOREIGN KEY(INSTANCE_ID, FLOW_NODE_ID) REFERENCES WF_INSTANCE_FLOW_NODE (INSTANCE_ID, FLOW_NODE_ID) DEFERRABLE)
ALTER TABLE WF_INSTANCE_FLOW_NODE ADD(CONSTRAINT FK_WF_FLOW_NODE_INSTANCE_NODE FOREIGN KEY(WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) REFERENCES WF_FLOW_NODE (WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) DEFERRABLE)
ALTER TABLE WF_FLOW_NODE ADD(CONSTRAINT FK_WF_LANE_FLOW_NODE FOREIGN KEY(WORKFLOW_ID, DEF_VERSION, LANE_ID) REFERENCES WF_LANE (WORKFLOW_ID, DEF_VERSION, LANE_ID) DEFERRABLE)
ALTER TABLE WF_BOUNDARY_EVENT ADD(CONSTRAINT FK_WF_FLOW_NODE_WF_BOUNDARY_EV FOREIGN KEY(WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) REFERENCES WF_FLOW_NODE (WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) DEFERRABLE)
ALTER TABLE WF_BOUNDARY_EVENT ADD(CONSTRAINT FK_WF_TRIGGER_BOUNDARY_EVENT FOREIGN KEY(WORKFLOW_ID, DEF_VERSION, BOUNDARY_EVENT_TRIGGER_ID) REFERENCES WF_BOUNDARY_EVENT_TRIGGER (WORKFLOW_ID, DEF_VERSION, BOUNDARY_EVENT_TRIGGER_ID) DEFERRABLE)
ALTER TABLE WF_BOUNDARY_EVENT ADD(CONSTRAINT FK_WF_TASK_BOUNDARY_EVENT FOREIGN KEY(WORKFLOW_ID, DEF_VERSION, ATTACHED_TASK_ID) REFERENCES WF_TASK (WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) DEFERRABLE)
ALTER TABLE WF_ACTIVE_USER_TASK ADD(CONSTRAINT FK_WF_ACTIVE_NODE_USER_TASK FOREIGN KEY(INSTANCE_ID, FLOW_NODE_ID) REFERENCES WF_ACTIVE_FLOW_NODE (INSTANCE_ID, FLOW_NODE_ID) DEFERRABLE)
ALTER TABLE WF_ACTIVE_GROUP_TASK ADD(CONSTRAINT FK_WF_ACTIVE_NODE_GROUP_TASK FOREIGN KEY(INSTANCE_ID, FLOW_NODE_ID) REFERENCES WF_ACTIVE_FLOW_NODE (INSTANCE_ID, FLOW_NODE_ID) DEFERRABLE)
ALTER TABLE WF_TASK ADD(CONSTRAINT FK_WF_FLOW_NODE_WF_TASK FOREIGN KEY(WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) REFERENCES WF_FLOW_NODE (WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) DEFERRABLE)
ALTER TABLE WF_EVENT ADD(CONSTRAINT FK_WF_FLOW_NODE_WF_EVENT FOREIGN KEY(WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) REFERENCES WF_FLOW_NODE (WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) DEFERRABLE)
ALTER TABLE WF_GATEWAY ADD(CONSTRAINT FK_WF_FLOW_NODE_WF_GATEWAY FOREIGN KEY(WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) REFERENCES WF_FLOW_NODE (WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) DEFERRABLE)